# Installs everything via Brew
# See https://docs.brew.sh/Manpage#bundle-subcommand
# To use, clone/copy this file somewhere, then "brew bundle install Brewfile"
# Assumes obviously that Brew is installed
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "awscli"
brew "bat"
brew "chezmoi"
brew "coreutils"
brew "curl"
brew "exa"
brew "git"
brew "gnu-getopt"
brew "go"
brew "graphviz"
brew "helm"
brew "jq"
brew "kubernetes-cli"
brew "kubeseal"
brew "node"
brew "pulumi"
brew "ruby"
brew "tree"
brew "wget"
cask "appcleaner"
cask "eul"
cask "iterm2"
cask "meld"
cask "google-chrome"
cask "visual-studio-code"
cask "spotify"
cask "firefox"
cask "slack"
cask "mambaforge"
cask "itsycal"
cask "github"